// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MacroProcesor {
    
    
    public partial class ResultsWindow {
        
        private Gtk.Fixed fixed4;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TextView textview5;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MacroProcesor.ResultsWindow
            this.Name = "MacroProcesor.ResultsWindow";
            this.Title = Mono.Unix.Catalog.GetString("ResultsWindow");
            this.WindowPosition = ((Gtk.WindowPosition)(3));
            // Container child MacroProcesor.ResultsWindow.Gtk.Container+ContainerChild
            this.fixed4 = new Gtk.Fixed();
            this.fixed4.Name = "fixed4";
            this.fixed4.HasWindow = false;
            // Container child fixed4.Gtk.Fixed+FixedChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.WidthRequest = 400;
            this.GtkScrolledWindow.HeightRequest = 400;
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.textview5 = new Gtk.TextView();
            this.textview5.CanFocus = true;
            this.textview5.Name = "textview5";
            this.GtkScrolledWindow.Add(this.textview5);
            this.fixed4.Add(this.GtkScrolledWindow);
            Gtk.Fixed.FixedChild w2 = ((Gtk.Fixed.FixedChild)(this.fixed4[this.GtkScrolledWindow]));
            w2.X = 11;
            w2.Y = 12;
            this.Add(this.fixed4);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 418;
            this.DefaultHeight = 444;
            this.Show();
        }
    }
}
