// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Fixed fixed3;
    
    private Gtk.ScrolledWindow GtkScrolledWindow1;
    
    private Gtk.TextView textview4;
    
    private Gtk.ScrolledWindow GtkScrolledWindow;
    
    private Gtk.TextView textview3;
    
    private Gtk.FileChooserButton filechooserbutton1;
    
    private Gtk.Button button3;
    
    private Gtk.Button button6;
    
    private Gtk.Button button7;
    
    private Gtk.Button button5;
    
    private Gtk.FileChooserButton filechooserbutton2;
    
    private Gtk.Button button8;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.WidthRequest = 630;
        this.HeightRequest = 460;
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(3));
        this.AllowGrow = false;
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.fixed3 = new Gtk.Fixed();
        this.fixed3.Name = "fixed3";
        this.fixed3.HasWindow = false;
        // Container child fixed3.Gtk.Fixed+FixedChild
        this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow1.WidthRequest = 300;
        this.GtkScrolledWindow1.HeightRequest = 380;
        this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
        this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
        this.textview4 = new Gtk.TextView();
        this.textview4.CanFocus = true;
        this.textview4.Name = "textview4";
        this.GtkScrolledWindow1.Add(this.textview4);
        this.fixed3.Add(this.GtkScrolledWindow1);
        Gtk.Fixed.FixedChild w2 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.GtkScrolledWindow1]));
        w2.X = 323;
        w2.Y = 13;
        // Container child fixed3.Gtk.Fixed+FixedChild
        this.GtkScrolledWindow = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow.WidthRequest = 300;
        this.GtkScrolledWindow.HeightRequest = 380;
        this.GtkScrolledWindow.Name = "GtkScrolledWindow";
        this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
        this.textview3 = new Gtk.TextView();
        this.textview3.CanFocus = true;
        this.textview3.Name = "textview3";
        this.GtkScrolledWindow.Add(this.textview3);
        this.fixed3.Add(this.GtkScrolledWindow);
        Gtk.Fixed.FixedChild w4 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.GtkScrolledWindow]));
        w4.X = 5;
        w4.Y = 15;
        // Container child fixed3.Gtk.Fixed+FixedChild
        this.filechooserbutton1 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select A File"), ((Gtk.FileChooserAction)(0)));
        this.filechooserbutton1.WidthRequest = 100;
        this.filechooserbutton1.Name = "filechooserbutton1";
        this.fixed3.Add(this.filechooserbutton1);
        Gtk.Fixed.FixedChild w5 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.filechooserbutton1]));
        w5.X = 6;
        w5.Y = 397;
        // Container child fixed3.Gtk.Fixed+FixedChild
        this.button3 = new Gtk.Button();
        this.button3.WidthRequest = 80;
        this.button3.CanFocus = true;
        this.button3.Name = "button3";
        this.button3.UseUnderline = true;
        this.button3.Label = Mono.Unix.Catalog.GetString("Load");
        this.fixed3.Add(this.button3);
        Gtk.Fixed.FixedChild w6 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.button3]));
        w6.X = 110;
        w6.Y = 397;
        // Container child fixed3.Gtk.Fixed+FixedChild
        this.button6 = new Gtk.Button();
        this.button6.WidthRequest = 80;
        this.button6.CanFocus = true;
        this.button6.Name = "button6";
        this.button6.UseUnderline = true;
        this.button6.Label = Mono.Unix.Catalog.GetString("Save");
        this.fixed3.Add(this.button6);
        Gtk.Fixed.FixedChild w7 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.button6]));
        w7.X = 193;
        w7.Y = 397;
        // Container child fixed3.Gtk.Fixed+FixedChild
        this.button7 = new Gtk.Button();
        this.button7.WidthRequest = 80;
        this.button7.CanFocus = true;
        this.button7.Name = "button7";
        this.button7.UseUnderline = true;
        this.button7.Label = Mono.Unix.Catalog.GetString("Save");
        this.fixed3.Add(this.button7);
        Gtk.Fixed.FixedChild w8 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.button7]));
        w8.X = 527;
        w8.Y = 395;
        // Container child fixed3.Gtk.Fixed+FixedChild
        this.button5 = new Gtk.Button();
        this.button5.WidthRequest = 80;
        this.button5.CanFocus = true;
        this.button5.Name = "button5";
        this.button5.UseUnderline = true;
        this.button5.Label = Mono.Unix.Catalog.GetString("Load");
        this.fixed3.Add(this.button5);
        Gtk.Fixed.FixedChild w9 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.button5]));
        w9.X = 444;
        w9.Y = 395;
        // Container child fixed3.Gtk.Fixed+FixedChild
        this.filechooserbutton2 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select A File"), ((Gtk.FileChooserAction)(0)));
        this.filechooserbutton2.WidthRequest = 100;
        this.filechooserbutton2.Name = "filechooserbutton2";
        this.fixed3.Add(this.filechooserbutton2);
        Gtk.Fixed.FixedChild w10 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.filechooserbutton2]));
        w10.X = 340;
        w10.Y = 395;
        // Container child fixed3.Gtk.Fixed+FixedChild
        this.button8 = new Gtk.Button();
        this.button8.WidthRequest = 80;
        this.button8.CanFocus = true;
        this.button8.Name = "button8";
        this.button8.UseUnderline = true;
        this.button8.Label = Mono.Unix.Catalog.GetString("Run");
        this.fixed3.Add(this.button8);
        Gtk.Fixed.FixedChild w11 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.button8]));
        w11.X = 274;
        w11.Y = 426;
        this.Add(this.fixed3);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 642;
        this.DefaultHeight = 489;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.button3.Clicked += new System.EventHandler(this.OnButton3Clicked);
        this.button6.Clicked += new System.EventHandler(this.OnButton6Clicked);
        this.button7.Clicked += new System.EventHandler(this.OnButton7Clicked);
        this.button5.Clicked += new System.EventHandler(this.OnButton5Clicked);
        this.button8.Clicked += new System.EventHandler(this.OnButton8Clicked);
    }
}
